import { Station } from '../common/types';

const updated = new Date(Date.now() - 4 * 60_000).toISOString();

export const STATIONS: Station[] = [
  {
    id: 'cw-orchard-central',
    name: 'Orchard Central',
    address: '181 Orchard Road',
    postalCode: '238896',
    latitude: 1.3008,
    longitude: 103.8393,
    operator: 'Charge+',
    connectors: [
      { type: 'CCS2', powerKw: 120, total: 4, available: 2, status: 'available' },
      { type: 'Type 2', powerKw: 22, total: 6, available: 3, status: 'available' },
    ],
    pricePerKwh: 0.62,
    source: 'Cached demo data',
    lastUpdated: updated,
  },
  {
    id: 'cw-plaza-singapura',
    name: 'Plaza Singapura',
    address: '68 Orchard Road',
    postalCode: '238839',
    latitude: 1.3005,
    longitude: 103.8452,
    operator: 'SP Mobility',
    connectors: [
      { type: 'CCS2', powerKw: 50, total: 6, available: 4, status: 'available' },
      { type: 'Type 2', powerKw: 22, total: 4, available: 1, status: 'available' },
    ],
    pricePerKwh: 0.55,
    source: 'Cached demo data',
    lastUpdated: updated,
  },
  {
    id: 'cw-suntec-city',
    name: 'Suntec City',
    address: '3 Temasek Boulevard',
    postalCode: '038983',
    latitude: 1.2947,
    longitude: 103.8583,
    operator: 'Shell Recharge',
    connectors: [
      { type: 'CCS2', powerKw: 180, total: 4, available: 1, status: 'available' },
      { type: 'CHAdeMO', powerKw: 50, total: 2, available: 0, status: 'busy' },
    ],
    pricePerKwh: 0.69,
    source: 'Cached demo data',
    lastUpdated: updated,
  },
  {
    id: 'cw-great-world',
    name: 'Great World',
    address: '1 Kim Seng Promenade',
    postalCode: '237994',
    latitude: 1.2938,
    longitude: 103.8319,
    operator: 'Bluecharge',
    connectors: [
      { type: 'CCS2', powerKw: 60, total: 4, available: 0, status: 'busy' },
      { type: 'Type 2', powerKw: 22, total: 8, available: 2, status: 'available' },
    ],
    pricePerKwh: 0.48,
    source: 'Cached demo data',
    lastUpdated: updated,
  },
  {
    id: 'cw-marina-bay',
    name: 'Marina Bay Financial Centre',
    address: '8A Marina Boulevard',
    postalCode: '018984',
    latitude: 1.2795,
    longitude: 103.8545,
    operator: 'SP Mobility',
    connectors: [
      { type: 'CCS2', powerKw: 150, total: 6, available: 3, status: 'available' },
      { type: 'Type 2', powerKw: 22, total: 6, available: 4, status: 'available' },
    ],
    pricePerKwh: 0.58,
    source: 'Cached demo data',
    lastUpdated: updated,
  },
  {
    id: 'cw-vivo-city',
    name: 'VivoCity',
    address: '1 HarbourFront Walk',
    postalCode: '098585',
    latitude: 1.2644,
    longitude: 103.8223,
    operator: 'Charge+',
    connectors: [
      { type: 'CCS2', powerKw: 100, total: 4, available: 2, status: 'available' },
      { type: 'Type 2', powerKw: 22, total: 10, available: 5, status: 'available' },
      { type: 'CHAdeMO', powerKw: 50, total: 2, available: 1, status: 'available' },
    ],
    pricePerKwh: null,
    source: 'Cached demo data',
    lastUpdated: updated,
  },
  {
    id: 'cw-jurong-gateway',
    name: 'JEM Jurong Gateway',
    address: '50 Jurong Gateway Road',
    postalCode: '608549',
    latitude: 1.3332,
    longitude: 103.7431,
    operator: 'Shell Recharge',
    connectors: [
      { type: 'CCS2', powerKw: 200, total: 8, available: 5, status: 'available' },
      { type: 'CHAdeMO', powerKw: 50, total: 2, available: 1, status: 'available' },
    ],
    pricePerKwh: 0.65,
    source: 'Cached demo data',
    lastUpdated: updated,
  },
  {
    id: 'cw-tampines-hub',
    name: 'Our Tampines Hub',
    address: '1 Tampines Walk',
    postalCode: '528523',
    latitude: 1.3529,
    longitude: 103.9404,
    operator: 'SP Mobility',
    connectors: [
      { type: 'CCS2', powerKw: 120, total: 6, available: 2, status: 'available' },
      { type: 'Type 2', powerKw: 22, total: 8, available: null, status: 'unknown' },
    ],
    pricePerKwh: 0.53,
    source: 'Cached demo data',
    lastUpdated: new Date(Date.now() - 36 * 60_000).toISOString(),
  },
  {
    id: 'cw-paya-lebar',
    name: 'Paya Lebar Quarter',
    address: '10 Paya Lebar Road',
    postalCode: '409057',
    latitude: 1.3175,
    longitude: 103.8927,
    operator: 'Bluecharge',
    connectors: [
      { type: 'Type 2', powerKw: 22, total: 12, available: 7, status: 'available' },
      { type: 'CCS2', powerKw: 80, total: 4, available: 0, status: 'busy' },
    ],
    pricePerKwh: 0.46,
    source: 'Cached demo data',
    lastUpdated: updated,
  },
  {
    id: 'cw-changi-jewel',
    name: 'Jewel Changi Airport',
    address: '78 Airport Boulevard',
    postalCode: '819666',
    latitude: 1.3602,
    longitude: 103.9899,
    operator: 'Charge+',
    connectors: [
      { type: 'CCS2', powerKw: 180, total: 10, available: 6, status: 'available' },
      { type: 'CHAdeMO', powerKw: 50, total: 2, available: 0, status: 'offline' },
    ],
    pricePerKwh: 0.71,
    source: 'Cached demo data',
    lastUpdated: updated,
  },
];

export const KNOWN_LOCATIONS: Record<string, { latitude: number; longitude: number; label: string }> = {
  orchard: { latitude: 1.3048, longitude: 103.8318, label: 'Orchard Road' },
  '238896': { latitude: 1.3008, longitude: 103.8393, label: '238896' },
  marina: { latitude: 1.2834, longitude: 103.8607, label: 'Marina Bay' },
  jurong: { latitude: 1.3332, longitude: 103.7431, label: 'Jurong East' },
  tampines: { latitude: 1.3521, longitude: 103.9446, label: 'Tampines' },
  changi: { latitude: 1.3571, longitude: 103.9884, label: 'Changi Airport' },
  singapore: { latitude: 1.2903, longitude: 103.8519, label: 'Singapore' },
};
